### ISSUE TITLE
package version

### ISSUE THREAD

**Issue by yuntaodu** [vturrisi/disef#1]
Hi, thanks for your great work. Could you please share the package version in the requirement.txt?

**Comment by vturrisi** [comment]
Hey. I think there shouldn't be any issue with other library versions apart from lightning. Did you try installing with the current requirements file?

**Comment by yuntaodu** [comment]
Thanks, I have installed the packages successfully. I have another question. During the generation process in synthetic_augmentation_pipeline.py,  does the scheduler need to be reset in each generation(batch)?  There are running errors at the second batch.
![image](https://github.com/vturrisi/disef/assets/24802494/aafda681-ec97-4029-99fa-dd1db489b25e)

**Comment by Fodark** [comment]
I faced the same issue recently in another project due to (probably) a new version of diffusers.
When the code was published I was using `diffusers==0.17.1`, can you confirm that this version does not lead to this issue?

**Comment by yuntaodu** [comment]
My current version is diffusers==0.26.3, it also faces this problem.

**Comment by yuntaodu** [comment]
Thanks for your reply, after default installation, my current version is diffusers==0.26.3, when I  change to diffusers==0.17.1, the error is solved. Maybe it is better to set diffusers==0.17.1 in the requirement.txt

**Comment by Fodark** [comment]
Thank you for confirming, will update the requirements accordingly!
